interface WidgetColorTemplateInterface {
  id: string;
  name: string;
  backgroundColor: string;
  textColor: string;
  thumbnailColor: string;
  buttonColor: string;
  buttonTextColor: string;
}
export const palettes: WidgetColorTemplateInterface[] = [
  {
    id: "",
    name: "Custom Color Palette",
    backgroundColor: "",
    textColor: "",
    thumbnailColor: "",
    buttonColor: "",
    buttonTextColor: "",
  },
  {
    id: "1",
    name: "Default Palette",
    backgroundColor: "#1C1C20",
    textColor: "#FFD6AF",
    thumbnailColor: "#EE5F1D",
    buttonColor: "#1C1C20",
    buttonTextColor: "#FFD6AF",
  },
  {
    id: "2",
    name: "Beige Palette",
    backgroundColor: "#d49c6b",
    textColor: "#252b31",
    thumbnailColor: "#c1c8c7",
    buttonColor: "#c1c8c7",
    buttonTextColor: "#252b31",
  },
  {
    id: "3",
    name: "Military Palette",
    backgroundColor: "#ADAB76",
    textColor: "#0F211A",
    thumbnailColor: "#666B3A",
    buttonColor: "#ACA69F",
    buttonTextColor: "#0F211A",
  },
  {
    id: "4",
    name: "Reddish Palette",
    backgroundColor: "#562C2C",
    textColor: "#F5DFBB",
    thumbnailColor: "#F2542D",
    buttonColor: "#F5DFBB",
    buttonTextColor: "#562C2C",
  },
  {
    id: "5",
    name: "Shades of Blue Palette",
    backgroundColor: "#2A324B",
    textColor: "#E1E5EE",
    thumbnailColor: "#767B91",
    buttonColor: "#C7CCDB",
    buttonTextColor: "#2A324B",
  },
  {
    id: "6",
    name: "Delicate Palette",
    backgroundColor: "#C7AABC",
    textColor: "#02334A",
    thumbnailColor: "#513E5C",
    buttonColor: "#A9BCC6",
    buttonTextColor: "#02334A",
  },
  {
    id: "7",
    name: "Brazilian Palette",
    backgroundColor: "#0B8639",
    textColor: "#FEDF00",
    thumbnailColor: "#1C47A0",
    buttonColor: "#1C47A0",
    buttonTextColor: "#FFFFFF",
  },
  {
    id: "8",
    name: "Indian Palette",
    backgroundColor: "#FF9933",
    textColor: "#FFFFFF",
    thumbnailColor: "#138808",
    buttonColor: "#FFFFFF",
    buttonTextColor: "#138808",
  },
  {
    id: "9",
    name: "American Palette",
    backgroundColor: "#002868",
    textColor: "#FFFFFF",
    thumbnailColor: "#BF0A30",
    buttonColor: "#BF0A30",
    buttonTextColor: "#FFFFFF",
  },
  {
    id: "10",
    name: "Facebook Palette",
    backgroundColor: "#3B5998",
    textColor: "#FFFFFF",
    thumbnailColor: "#8B9DC3",
    buttonColor: "#FFFFFF",
    buttonTextColor: "#3B5998",
  },
  {
    id: "11",
    name: "TikTok Palette",
    backgroundColor: "#FFFFFF",
    textColor: "#404040",
    thumbnailColor: "#EE1D52",
    buttonColor: "#69C9D0",
    buttonTextColor: "#FFFFFF",
  },
  {
    id: "12",
    name: "Black and White Palette",
    backgroundColor: "#f5f5f5",
    textColor: "#404040",
    thumbnailColor: "#404040",
    buttonColor: "#404040",
    buttonTextColor: "#FFFFFF",
  },
  {
    id: "13",
    name: "Christmas Palette",
    backgroundColor: "#BB2528",
    textColor: "#FFFFFF",
    thumbnailColor: "#146B3A",
    buttonColor: "#146B3A",
    buttonTextColor: "#FFFFFF",
  },
];
